# Generated by Django 4.0.5 on 2022-06-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='body',
        ),
    ]
